/* This file was generated by lv6 version v6.105.0. */
/*  lv6 for.lus -2c -n STABLE */
/* on 0cc890029dcd the 15/06/2022 at 04:00:47 */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "lustre_consts.h"

// User typedef 
#ifndef _for_STABLE_TYPES
#define _for_STABLE_TYPES
// Memoryless soc ctx typedef 
// Memoryfull soc ctx typedef 
#endif // end of  _for_STABLE_TYPES
void for_STABLE_step(_boolean ,_integer *);