/* This file was generated by lv6 version v6.105.0. */
/*  lv6 for.lus -2c -n STABLE */
/* on 0cc890029dcd the 15/06/2022 at 04:00:47 */
#include "if_STABLE.h"
//// Defining step functions
// Step function(s) for for_STABLE_ctx
void for_STABLE_step(_boolean in_judge,_integer *out_C){

   if (in_judge == _true) {
     *out_C = 20;
   } else {
     *out_C = 30;
   }

} // End of for_STABLE_step