/* This file was generated by lv6 version v6.105.0. */
/*  lv6 for.lus -2c -n STABLE */
/* on 0cc890029dcd the 15/06/2022 at 04:00:47 */

#ifndef _SOC2C_PREDEF_TYPES
#define _SOC2C_PREDEF_TYPES
typedef int _boolean;
typedef int _integer;
typedef char* _string;
typedef double _real;
typedef double _double;
typedef float _float;
#define _false 0
#define _true 1
#endif